steps:
  - label: 'Triggering pipelines'
    plugins:
      - chronotc/monorepo-diff#v2.3.0:
          diff: 'git diff --name-only HEAD~1'
          watch:
            - path: '**/*.!m*'
              config:
                command: 'echo deploy-bar'
